### ISSUE TITLE
How is data are vector3?

### ISSUE THREAD

**Issue by YenYaoHan** [kkartavenka/FastDtw.CSharp#1]
Hi Thanks for your great work.

I would wanna know if i have two vector3 list, (x,y,z)
such as List<Vector3> pathA and List<Vector3> pathB,

is it can work on your algorithm? Is it possible to provide a sample code?

**Comment by kkartavenka** [comment]
@YenYaoHan 
Vector3 contains 3 float variables. I am not sure what path you want to compute between two vector points.

Overall, the algorithm accepts two arrays/spans, not three-dimensional vectors. However, you can modify the code to consume vectors and compute the distance between two points for the cost matrix with ways suited your needs.
